/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.ApplicationFactory;
import model.Disco;
import model.Genero;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 * @author User
 */
public class Menu extends javax.swing.JFrame {

  private final ApplicationFactory factory;
  private List<Genero> listaGeneros;
  private List<Disco> listaDiscos;
  private DefaultTableModel modelGeneros, modelDiscos;

  /**
   * Creates new form Menu
   */
  public Menu() {
    factory = new ApplicationFactory();
    initComponents();
    tela_home.setVisible(true);
    tela_sobre.setVisible(false);
    tela_cad_disco.setVisible(false);
    tela_cad_genero.setVisible(false);
    tela_consulta_disco.setVisible(false);
    tela_consulta_genero.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    setUndecorated(true);
    sideMenu = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    lb_cadastro = new javax.swing.JLabel();
    tab1_cad_disco = new javax.swing.JPanel();
    lb_cad_disco = new javax.swing.JLabel();
    tab2_cad_genero = new javax.swing.JPanel();
    lb_cad_genero = new javax.swing.JLabel();
    lb_consulta = new javax.swing.JLabel();
    tab3_consul_disco = new javax.swing.JPanel();
    lb_consul_disco = new javax.swing.JLabel();
    tab4_consul_genero = new javax.swing.JPanel();
    lb_consul_genero = new javax.swing.JLabel();
    topBar = new javax.swing.JPanel();
    btn_sobre = new javax.swing.JPanel();
    label_sobre = new javax.swing.JLabel();
    btn_desliga = new javax.swing.JPanel();
    label_desliga = new javax.swing.JLabel();
    home = new javax.swing.JPanel();
    tela_home = new javax.swing.JPanel();
    background = new javax.swing.JLabel();
    tela_sobre = new javax.swing.JPanel();
    andrey = new javax.swing.JLabel();
    ryan = new javax.swing.JLabel();
    painel_creditos = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    btn_voltar_sobre = new javax.swing.JPanel();
    label_voltar_sobre = new javax.swing.JLabel();
    tela_cad_disco = new javax.swing.JPanel();
    title_cad_disco = new javax.swing.JLabel();
    label_nome_disco = new javax.swing.JLabel();
    input_cad_disco_nome = new javax.swing.JTextField();
    label_ano = new javax.swing.JLabel();
    input_cad_disco_ano = new javax.swing.JTextField();
    label_genero = new javax.swing.JLabel();
    combo_box_genero = new javax.swing.JComboBox<>();
    btn_voltar_cad_disco = new javax.swing.JPanel();
    label_cancelar = new javax.swing.JLabel();
    btn_cadastrar_disco = new javax.swing.JPanel();
    label_cadastrar = new javax.swing.JLabel();
    tela_cad_genero = new javax.swing.JPanel();
    title_cad_genero = new javax.swing.JLabel();
    label_nome_gen = new javax.swing.JLabel();
    label_grupo = new javax.swing.JLabel();
    input_cad_genero_nome = new javax.swing.JTextField();
    combo_box_grupo = new javax.swing.JComboBox<>();
    btn_voltar_cad_gen = new javax.swing.JPanel();
    label_cancelar_gen = new javax.swing.JLabel();
    btn_cadastrar_genero = new javax.swing.JPanel();
    label_cadastrar_gen = new javax.swing.JLabel();
    tela_consulta_disco = new javax.swing.JPanel();
    title_con_disco = new javax.swing.JLabel();
    input_consulta_disco = new javax.swing.JTextField();
    btn_buscar_disco = new javax.swing.JPanel();
    label_buscar_disco = new javax.swing.JLabel();
    jScrollPane_disco = new javax.swing.JScrollPane();
    jTable_disco = new javax.swing.JTable();
    btn_voltar_con_disco = new javax.swing.JPanel();
    label_voltar_disco = new javax.swing.JLabel();
    tela_consulta_genero = new javax.swing.JPanel();
    title_con_genero = new javax.swing.JLabel();
    input_consulta_genero = new javax.swing.JTextField();
    btn_buscar_genero = new javax.swing.JPanel();
    label_buscar_gen = new javax.swing.JLabel();
    jScrollPane_genero = new javax.swing.JScrollPane();
    jTable_genero = new javax.swing.JTable();
    btn_voltar_con_gen = new javax.swing.JPanel();
    label_voltar_gen = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(239, 239, 239));

    sideMenu.setBackground(new java.awt.Color(51, 53, 51));
    sideMenu.setPreferredSize(new java.awt.Dimension(250, 0));

    logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logo.setIcon(new ImageIcon("viewImages/logo_album_cover.png")); // NOI18N

    lb_cadastro.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
    lb_cadastro.setForeground(new java.awt.Color(232, 237, 223));
    lb_cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_cadastro.setText("CADASTRO:");
    lb_cadastro.setPreferredSize(new java.awt.Dimension(220, 40));

    tab1_cad_disco.setBackground(new java.awt.Color(36, 36, 35));
    tab1_cad_disco.setPreferredSize(new java.awt.Dimension(105, 40));
    tab1_cad_disco.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tab1_cad_discoMouseClicked(evt);
      }
    });

    lb_cad_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lb_cad_disco.setForeground(new java.awt.Color(232, 237, 223));
    lb_cad_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_cad_disco.setText("Disco");

    javax.swing.GroupLayout tab1_cad_discoLayout = new javax.swing.GroupLayout(tab1_cad_disco);
    tab1_cad_disco.setLayout(tab1_cad_discoLayout);
    tab1_cad_discoLayout.setHorizontalGroup(
        tab1_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cad_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    tab1_cad_discoLayout.setVerticalGroup(
        tab1_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cad_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    tab2_cad_genero.setBackground(new java.awt.Color(36, 36, 35));
    tab2_cad_genero.setPreferredSize(new java.awt.Dimension(105, 40));
    tab2_cad_genero.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tab2_cad_generoMouseClicked(evt);
      }
    });

    lb_cad_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lb_cad_genero.setForeground(new java.awt.Color(232, 237, 223));
    lb_cad_genero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_cad_genero.setText("Gênero");

    javax.swing.GroupLayout tab2_cad_generoLayout = new javax.swing.GroupLayout(tab2_cad_genero);
    tab2_cad_genero.setLayout(tab2_cad_generoLayout);
    tab2_cad_generoLayout.setHorizontalGroup(
        tab2_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cad_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    tab2_cad_generoLayout.setVerticalGroup(
        tab2_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cad_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    lb_consulta.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
    lb_consulta.setForeground(new java.awt.Color(232, 237, 223));
    lb_consulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_consulta.setText("CONSULTA:");
    lb_consulta.setPreferredSize(new java.awt.Dimension(220, 40));

    tab3_consul_disco.setBackground(new java.awt.Color(36, 36, 35));
    tab3_consul_disco.setPreferredSize(new java.awt.Dimension(105, 40));
    tab3_consul_disco.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tab3_consul_discoMouseClicked(evt);
      }
    });

    lb_consul_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lb_consul_disco.setForeground(new java.awt.Color(232, 237, 223));
    lb_consul_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_consul_disco.setText("Disco");

    javax.swing.GroupLayout tab3_consul_discoLayout = new javax.swing.GroupLayout(tab3_consul_disco);
    tab3_consul_disco.setLayout(tab3_consul_discoLayout);
    tab3_consul_discoLayout.setHorizontalGroup(
        tab3_consul_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_consul_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
    );
    tab3_consul_discoLayout.setVerticalGroup(
        tab3_consul_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_consul_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    tab4_consul_genero.setBackground(new java.awt.Color(36, 36, 35));
    tab4_consul_genero.setPreferredSize(new java.awt.Dimension(105, 40));
    tab4_consul_genero.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tab4_consul_generoMouseClicked(evt);
      }
    });

    lb_consul_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    lb_consul_genero.setForeground(new java.awt.Color(232, 237, 223));
    lb_consul_genero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lb_consul_genero.setText("Gênero");

    javax.swing.GroupLayout tab4_consul_generoLayout = new javax.swing.GroupLayout(tab4_consul_genero);
    tab4_consul_genero.setLayout(tab4_consul_generoLayout);
    tab4_consul_generoLayout.setHorizontalGroup(
        tab4_consul_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_consul_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    tab4_consul_generoLayout.setVerticalGroup(
        tab4_consul_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_consul_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
    sideMenu.setLayout(sideMenuLayout);
    sideMenuLayout.setHorizontalGroup(
        sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(lb_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addComponent(tab1_cad_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(tab2_cad_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sideMenuLayout.createSequentialGroup()
                        .addComponent(tab3_consul_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tab4_consul_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    sideMenuLayout.setVerticalGroup(
        sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo)
                .addGap(22, 22, 22)
                .addComponent(lb_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab2_cad_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab1_cad_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lb_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab3_consul_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab4_consul_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
    );

    topBar.setBackground(new java.awt.Color(51, 53, 51));
    topBar.setPreferredSize(new java.awt.Dimension(600, 50));

    btn_sobre.setBackground(new java.awt.Color(36, 36, 35));
    btn_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btn_sobreMouseClicked();
      }
    });

    label_sobre.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    label_sobre.setForeground(new java.awt.Color(232, 237, 223));
    label_sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_sobre.setText("?");

    javax.swing.GroupLayout btn_sobreLayout = new javax.swing.GroupLayout(btn_sobre);
    btn_sobre.setLayout(btn_sobreLayout);
    btn_sobreLayout.setHorizontalGroup(
        btn_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_sobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
    );
    btn_sobreLayout.setVerticalGroup(
        btn_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    btn_desliga.setBackground(new java.awt.Color(36, 36, 35));

    label_desliga.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    label_desliga.setForeground(new java.awt.Color(232, 237, 223));
    label_desliga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_desliga.setText("X");
    label_desliga.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_desligaMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btn_desligaLayout = new javax.swing.GroupLayout(btn_desliga);
    btn_desliga.setLayout(btn_desligaLayout);
    btn_desligaLayout.setHorizontalGroup(
        btn_desligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_desliga, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
    );
    btn_desligaLayout.setVerticalGroup(
        btn_desligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_desliga, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
    topBar.setLayout(topBarLayout);
    topBarLayout.setHorizontalGroup(
        topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_desliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
    );
    topBarLayout.setVerticalGroup(
        topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addComponent(btn_desliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    home.setBackground(new java.awt.Color(245, 203, 92));
    home.setLayout(new javax.swing.OverlayLayout(home));

    tela_home.setBackground(new java.awt.Color(245, 203, 92));
    tela_home.setPreferredSize(new java.awt.Dimension(600, 450));

    background.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/home_wallpaper.png"))); // NOI18N

    javax.swing.GroupLayout tela_homeLayout = new javax.swing.GroupLayout(tela_home);
    tela_home.setLayout(tela_homeLayout);
    tela_homeLayout.setHorizontalGroup(
        tela_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    tela_homeLayout.setVerticalGroup(
        tela_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_homeLayout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
    );

    home.add(tela_home);

    tela_sobre.setBackground(new java.awt.Color(245, 203, 92));

    andrey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    andrey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/andrey.png"))); // NOI18N

    ryan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    ryan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewImages/ryan.png"))); // NOI18N

    painel_creditos.setBackground(new java.awt.Color(51, 53, 51));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(232, 237, 223));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("UNIVERSIDADE CRUZEIRO DO SUL, PAULISTA");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(232, 237, 223));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("CCP – 4° SEMESTRE (NOTURNO), ESTRUTURA DE DADOS II ");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(232, 237, 223));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Prof. Orlando da Silva Junior ");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(232, 237, 223));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Ryan Anthony de Brito de Toledo - 21136734");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(232, 237, 223));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Andrey Willians Silvestre Hubner - 21151750 ");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(232, 237, 223));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Projeto Prático ");

    javax.swing.GroupLayout painel_creditosLayout = new javax.swing.GroupLayout(painel_creditos);
    painel_creditos.setLayout(painel_creditosLayout);
    painel_creditosLayout.setHorizontalGroup(
        painel_creditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    painel_creditosLayout.setVerticalGroup(
        painel_creditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_creditosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap())
    );

    btn_voltar_sobre.setBackground(new java.awt.Color(51, 53, 51));

    label_voltar_sobre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    label_voltar_sobre.setForeground(new java.awt.Color(232, 237, 223));
    label_voltar_sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_voltar_sobre.setText("Voltar");
    label_voltar_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_voltar_sobreMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btn_voltar_sobreLayout = new javax.swing.GroupLayout(btn_voltar_sobre);
    btn_voltar_sobre.setLayout(btn_voltar_sobreLayout);
    btn_voltar_sobreLayout.setHorizontalGroup(
        btn_voltar_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_sobre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    btn_voltar_sobreLayout.setVerticalGroup(
        btn_voltar_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_sobre, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout tela_sobreLayout = new javax.swing.GroupLayout(tela_sobre);
    tela_sobre.setLayout(tela_sobreLayout);
    tela_sobreLayout.setHorizontalGroup(
        tela_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_sobreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(tela_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel_creditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tela_sobreLayout.createSequentialGroup()
                        .addComponent(andrey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addComponent(btn_voltar_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(ryan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
    );
    tela_sobreLayout.setVerticalGroup(
        tela_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_sobreLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(painel_creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tela_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_sobreLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tela_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(andrey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ryan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tela_sobreLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_voltar_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
    );

    home.add(tela_sobre);

    tela_cad_disco.setBackground(new java.awt.Color(245, 203, 92));

    title_cad_disco.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
    title_cad_disco.setForeground(new java.awt.Color(36, 36, 35));
    title_cad_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title_cad_disco.setText("Cadastro de Disco");

    label_nome_disco.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
    label_nome_disco.setForeground(new java.awt.Color(36, 36, 35));
    label_nome_disco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_nome_disco.setText("Nome:");

    input_cad_disco_nome.setBackground(new java.awt.Color(227, 252, 239));
    input_cad_disco_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    input_cad_disco_nome.setForeground(new java.awt.Color(36, 36, 35));
    input_cad_disco_nome.setCaretColor(new java.awt.Color(36, 36, 35));
    input_cad_disco_nome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        input_cad_disco_nomeActionPerformed();
      }
    });

    label_ano.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
    label_ano.setForeground(new java.awt.Color(36, 36, 35));
    label_ano.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_ano.setText("Ano:");

    input_cad_disco_ano.setBackground(new java.awt.Color(227, 252, 239));
    input_cad_disco_ano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    input_cad_disco_ano.setForeground(new java.awt.Color(36, 36, 35));
    input_cad_disco_ano.setCaretColor(new java.awt.Color(36, 36, 35));
    input_cad_disco_ano.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        input_cad_disco_anoActionPerformed();
      }
    });

    label_genero.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
    label_genero.setForeground(new java.awt.Color(36, 36, 35));
    label_genero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_genero.setText("Gênero:");

    combo_box_genero.setBackground(new java.awt.Color(227, 252, 239));
    combo_box_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    combo_box_genero.setForeground(new java.awt.Color(36, 36, 35));
    combo_box_genero.setMaximumRowCount(10);
    combo_box_genero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        combo_box_generoActionPerformed();
      }
    });

    btn_voltar_cad_disco.setBackground(new java.awt.Color(36, 36, 35));
    btn_voltar_cad_disco.setPreferredSize(new java.awt.Dimension(105, 40));

    label_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_cancelar.setForeground(new java.awt.Color(232, 237, 223));
    label_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_cancelar.setText("Cancelar");
    label_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_cancelarMouseClicked();
      }
    });

    javax.swing.GroupLayout btn_voltar_cad_discoLayout = new javax.swing.GroupLayout(btn_voltar_cad_disco);
    btn_voltar_cad_disco.setLayout(btn_voltar_cad_discoLayout);
    btn_voltar_cad_discoLayout.setHorizontalGroup(
        btn_voltar_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_voltar_cad_discoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btn_voltar_cad_discoLayout.setVerticalGroup(
        btn_voltar_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_voltar_cad_discoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    btn_cadastrar_disco.setBackground(new java.awt.Color(36, 36, 35));

    label_cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_cadastrar.setForeground(new java.awt.Color(232, 237, 223));
    label_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_cadastrar.setText("Cadastrar");

    javax.swing.GroupLayout btn_cadastrar_discoLayout = new javax.swing.GroupLayout(btn_cadastrar_disco);
    btn_cadastrar_disco.setLayout(btn_cadastrar_discoLayout);
    btn_cadastrar_discoLayout.setHorizontalGroup(
        btn_cadastrar_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cadastrar_discoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btn_cadastrar_discoLayout.setVerticalGroup(
        btn_cadastrar_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cadastrar_discoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    btn_cadastrar_disco.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent mouseEvent) {
        String nomeDisco = input_cad_disco_nome.getText();
        String anoDisco = input_cad_disco_ano.getText();
        if (nomeDisco.isEmpty() || anoDisco.isEmpty()) {
          JOptionPane.showMessageDialog(null, "Preencha o nome e ano do disco", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
          int indexSelecionado = combo_box_genero.getSelectedIndex();
          Genero generoSelecionado = indexSelecionado > -1 ?
              combo_box_genero.getItemAt(indexSelecionado) : null;
          factory.cadastrarDisco(nomeDisco, Integer.parseInt(anoDisco), generoSelecionado);
          JOptionPane.showMessageDialog(null, "Disco cadastrado com sucesso");
          limparCampos();
          label_cancelarMouseClicked();
        }
      }
    });

    javax.swing.GroupLayout tela_cad_discoLayout = new javax.swing.GroupLayout(tela_cad_disco);
    tela_cad_disco.setLayout(tela_cad_discoLayout);
    tela_cad_discoLayout.setHorizontalGroup(
        tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_cad_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tela_cad_discoLayout.createSequentialGroup()
                .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_nome_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_cad_discoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_voltar_cad_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_cad_discoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela_cad_discoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_cad_disco_nome)
                            .addGroup(tela_cad_discoLayout.createSequentialGroup()
                                .addComponent(input_cad_disco_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_box_genero, 0, 188, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
    );
    tela_cad_discoLayout.setVerticalGroup(
        tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_cad_discoLayout.createSequentialGroup()
                .addComponent(title_cad_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_cad_disco_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_cad_discoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(label_nome_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_cad_discoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(label_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela_cad_discoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_cad_disco_ano, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_box_genero))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(tela_cad_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_voltar_cad_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
    );

    home.add(tela_cad_disco);

    tela_cad_genero.setBackground(new java.awt.Color(245, 203, 92));

    title_cad_genero.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
    title_cad_genero.setForeground(new java.awt.Color(36, 36, 35));
    title_cad_genero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title_cad_genero.setText("Cadastro de Gênero");
    title_cad_genero.setPreferredSize(new java.awt.Dimension(600, 110));

    label_nome_gen.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
    label_nome_gen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_nome_gen.setText("Nome:");

    label_grupo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
    label_grupo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    label_grupo.setText("Grupo:");

    input_cad_genero_nome.setBackground(new java.awt.Color(227, 252, 239));
    input_cad_genero_nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    input_cad_genero_nome.setForeground(new Color(36, 36, 35));
    input_cad_genero_nome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        input_cad_genero_nomeActionPerformed(evt);
      }
    });

    combo_box_grupo.setBackground(new java.awt.Color(227, 252, 239));
    combo_box_grupo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    combo_box_grupo.setMaximumRowCount(10);
    btn_voltar_cad_gen.setBackground(new Color(36, 36, 35));

    label_cancelar_gen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_cancelar_gen.setForeground(new java.awt.Color(232, 237, 223));
    label_cancelar_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_cancelar_gen.setText("Cancelar");
    label_cancelar_gen.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_cancelar_genMouseClicked();
      }
    });

    javax.swing.GroupLayout btn_voltar_cad_genLayout = new javax.swing.GroupLayout(btn_voltar_cad_gen);
    btn_voltar_cad_gen.setLayout(btn_voltar_cad_genLayout);
    btn_voltar_cad_genLayout.setHorizontalGroup(
        btn_voltar_cad_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cancelar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
    );
    btn_voltar_cad_genLayout.setVerticalGroup(
        btn_voltar_cad_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cancelar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    btn_cadastrar_genero.setBackground(new java.awt.Color(36, 36, 35));

    label_cadastrar_gen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_cadastrar_gen.setForeground(new java.awt.Color(232, 237, 223));
    label_cadastrar_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_cadastrar_gen.setText("Cadastrar");

    javax.swing.GroupLayout btn_cadastrar_generoLayout = new javax.swing.GroupLayout(btn_cadastrar_genero);
    btn_cadastrar_genero.setLayout(btn_cadastrar_generoLayout);
    btn_cadastrar_generoLayout.setHorizontalGroup(
        btn_cadastrar_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cadastrar_gen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
    );
    btn_cadastrar_generoLayout.setVerticalGroup(
        btn_cadastrar_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_cadastrar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    btn_cadastrar_genero.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent mouseEvent) {
        if (input_cad_genero_nome.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Preencha o nome do novo gênero", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
          int indexSelecionado = combo_box_grupo.getSelectedIndex();
          Genero generoSelecionado = indexSelecionado > -1 ?
              combo_box_grupo.getItemAt(indexSelecionado) : null;
          factory.cadastrarGenero(input_cad_genero_nome.getText(), generoSelecionado);
          JOptionPane.showMessageDialog(null, "Gênero cadastrado com sucesso");
          limparCampos();
          label_cancelar_genMouseClicked();
        }
      }
    });

    javax.swing.GroupLayout tela_cad_generoLayout = new javax.swing.GroupLayout(tela_cad_genero);
    tela_cad_genero.setLayout(tela_cad_generoLayout);
    tela_cad_generoLayout.setHorizontalGroup(
        tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_cad_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_cad_generoLayout.createSequentialGroup()
                .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tela_cad_generoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_voltar_cad_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label_nome_gen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_grupo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_cad_generoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_box_grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_cad_genero_nome)))
                    .addGroup(tela_cad_generoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
    );
    tela_cad_generoLayout.setVerticalGroup(
        tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_cad_generoLayout.createSequentialGroup()
                .addComponent(title_cad_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_nome_gen)
                    .addComponent(input_cad_genero_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_box_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(tela_cad_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_voltar_cad_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cadastrar_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
    );

    home.add(tela_cad_genero);

    tela_consulta_disco.setBackground(new java.awt.Color(245, 203, 92));

    title_con_disco.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
    title_con_disco.setForeground(new java.awt.Color(36, 36, 35));
    title_con_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title_con_disco.setText("Consulta de Disco");

    input_consulta_disco.setBackground(new java.awt.Color(227, 252, 239));
    input_consulta_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    input_consulta_disco.setForeground(new java.awt.Color(36, 36, 35));

    btn_buscar_disco.setBackground(new java.awt.Color(51, 53, 51));

    label_buscar_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_buscar_disco.setForeground(new java.awt.Color(232, 237, 223));
    label_buscar_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_buscar_disco.setText("Buscar");

    javax.swing.GroupLayout btn_buscar_discoLayout = new javax.swing.GroupLayout(btn_buscar_disco);
    btn_buscar_disco.setLayout(btn_buscar_discoLayout);
    btn_buscar_disco.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        String filtro = input_consulta_disco.getText();
        limparTabelaDiscos();
        listaDiscos = filtro.isEmpty() ?
                factory.getTodosDiscos() :
                factory.buscarDiscos(filtro);
        listaDiscos.forEach(disco -> {
          String genero = disco.getGenero() != null ?
                  disco.getGenero().getNome() :
                  "";
          modelDiscos.addRow(new Object[]{disco.getIdDisco(), disco.getTitulo(), disco.getAno(), genero});
        });
      }
    });
    btn_buscar_discoLayout.setHorizontalGroup(
        btn_buscar_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_buscar_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
    );
    btn_buscar_discoLayout.setVerticalGroup(
        btn_buscar_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_buscar_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jScrollPane_disco.setBackground(new java.awt.Color(36, 36, 35));
    jScrollPane_disco.setForeground(new java.awt.Color(232, 237, 223));
    jScrollPane_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    jTable_disco.setBackground(new java.awt.Color(51, 53, 51));
    jTable_disco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jTable_disco.setForeground(new java.awt.Color(232, 237, 223));
    jTable_disco.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{

        },
        new String[]{
            "ID", "TÍTULO", "ANO", "GÊNERO"
        }
    ) {
      final Class[] types = new Class[]{
          java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      final boolean[] canEdit = new boolean[]{
          false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });
    modelDiscos = (DefaultTableModel) jTable_disco.getModel();
    jTable_disco.setGridColor(new java.awt.Color(0, 0, 0));
    jTable_disco.setSelectionBackground(new java.awt.Color(227, 252, 239));
    jScrollPane_disco.setViewportView(jTable_disco);

    btn_voltar_con_disco.setBackground(new java.awt.Color(51, 53, 51));

    label_voltar_disco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_voltar_disco.setForeground(new java.awt.Color(232, 237, 223));
    label_voltar_disco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_voltar_disco.setText("Voltar");
    label_voltar_disco.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_voltar_discoMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btn_voltar_con_discoLayout = new javax.swing.GroupLayout(btn_voltar_con_disco);
    btn_voltar_con_disco.setLayout(btn_voltar_con_discoLayout);
    btn_voltar_con_discoLayout.setHorizontalGroup(
        btn_voltar_con_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
    );
    btn_voltar_con_discoLayout.setVerticalGroup(
        btn_voltar_con_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout tela_consulta_discoLayout = new javax.swing.GroupLayout(tela_consulta_disco);
    tela_consulta_disco.setLayout(tela_consulta_discoLayout);
    tela_consulta_discoLayout.setHorizontalGroup(
        tela_consulta_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_con_disco, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(tela_consulta_discoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(tela_consulta_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_consulta_discoLayout.createSequentialGroup()
                        .addComponent(btn_voltar_con_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tela_consulta_discoLayout.createSequentialGroup()
                        .addGroup(tela_consulta_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(tela_consulta_discoLayout.createSequentialGroup()
                                .addComponent(input_consulta_disco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscar_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86))))
    );
    tela_consulta_discoLayout.setVerticalGroup(
        tela_consulta_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_consulta_discoLayout.createSequentialGroup()
                .addComponent(title_con_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(tela_consulta_discoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_consulta_disco)
                    .addComponent(btn_buscar_disco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane_disco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_voltar_con_disco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
    );

    home.add(tela_consulta_disco);

    tela_consulta_genero.setBackground(new java.awt.Color(245, 203, 92));

    title_con_genero.setFont(new java.awt.Font("Segoe UI", 0, 44)); // NOI18N
    title_con_genero.setForeground(new java.awt.Color(36, 36, 35));
    title_con_genero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title_con_genero.setText("Consulta de Gênero");

    input_consulta_genero.setBackground(new java.awt.Color(227, 252, 239));
    input_consulta_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    input_consulta_genero.setForeground(new java.awt.Color(36, 36, 35));

    btn_buscar_genero.setBackground(new java.awt.Color(51, 53, 51));

    label_buscar_gen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_buscar_gen.setForeground(new java.awt.Color(232, 237, 223));
    label_buscar_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_buscar_gen.setText("Buscar");

    javax.swing.GroupLayout btn_buscar_generoLayout = new javax.swing.GroupLayout(btn_buscar_genero);
    btn_buscar_genero.setLayout(btn_buscar_generoLayout);
    btn_buscar_generoLayout.setHorizontalGroup(
        btn_buscar_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_buscar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
    );
    btn_buscar_genero.addMouseListener(new MouseAdapter() {
      @Override
      public void mouseClicked(MouseEvent e) {
        String filtro = input_consulta_genero.getText();
        limparTabelaGeneros();
        listaGeneros = filtro.isEmpty() ?
                factory.getTodosGeneros() :
                factory.buscarGeneros(filtro);
        listaGeneros.forEach(genero -> {
          if (genero != null) {
            String possuiSubgenero = genero.possuiSubgenero() ?
                    "Sim" :
                    "Não";
            modelGeneros.addRow(new Object[]{genero.getIdGenero(), genero.getNome(), genero.getNomeGeneroPai(), possuiSubgenero});
          }
        });
      }
    });
    btn_buscar_generoLayout.setVerticalGroup(
        btn_buscar_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_buscar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jScrollPane_genero.setBackground(new java.awt.Color(36, 36, 35));
    jScrollPane_genero.setForeground(new java.awt.Color(232, 237, 223));
    jScrollPane_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    jTable_genero.setBackground(new java.awt.Color(51, 53, 51));
    jTable_genero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    jTable_genero.setForeground(new java.awt.Color(232, 237, 223));
    jTable_genero.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{

        },
        new String[]{
            "ID", "NOME", "GRUPO", "Possui Subg."
        }
    ) {
      final Class[] types = new Class[]{
          java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      final boolean[] canEdit = new boolean[]{
          false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });
    modelGeneros = (DefaultTableModel) jTable_genero.getModel();
    jTable_genero.setGridColor(new java.awt.Color(0, 0, 0));
    jTable_genero.setSelectionBackground(new java.awt.Color(227, 252, 239));
    jScrollPane_genero.setViewportView(jTable_genero);

    btn_voltar_con_gen.setBackground(new java.awt.Color(51, 53, 51));

    label_voltar_gen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    label_voltar_gen.setForeground(new java.awt.Color(232, 237, 223));
    label_voltar_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_voltar_gen.setText("Voltar");
    label_voltar_gen.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        label_voltar_genMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout btn_voltar_con_genLayout = new javax.swing.GroupLayout(btn_voltar_con_gen);
    btn_voltar_con_gen.setLayout(btn_voltar_con_genLayout);
    btn_voltar_con_genLayout.setHorizontalGroup(
        btn_voltar_con_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
    );
    btn_voltar_con_genLayout.setVerticalGroup(
        btn_voltar_con_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_voltar_gen, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout tela_consulta_generoLayout = new javax.swing.GroupLayout(tela_consulta_genero);
    tela_consulta_genero.setLayout(tela_consulta_generoLayout);
    tela_consulta_generoLayout.setHorizontalGroup(
        tela_consulta_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_con_genero, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(tela_consulta_generoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(tela_consulta_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela_consulta_generoLayout.createSequentialGroup()
                        .addComponent(btn_voltar_con_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tela_consulta_generoLayout.createSequentialGroup()
                        .addGroup(tela_consulta_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(tela_consulta_generoLayout.createSequentialGroup()
                                .addComponent(input_consulta_genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscar_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86))))
    );
    tela_consulta_generoLayout.setVerticalGroup(
        tela_consulta_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_consulta_generoLayout.createSequentialGroup()
                .addComponent(title_con_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(tela_consulta_generoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_consulta_genero)
                    .addComponent(btn_buscar_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_voltar_con_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
    );

    home.add(tela_consulta_genero);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  // Eerie Black: 36,36,35
  // Alabaster: 232,237,223 (white)
  private void tab1_cad_discoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1_cad_discoMouseClicked
    limparTabelaGeneros();
    limparTabelaDiscos();
    listaGeneros = factory.getTodosGeneros();
    combo_box_genero.setModel(new javax.swing.DefaultComboBoxModel<>(listaGeneros.toArray(new Genero[0])));
    tela_home.setVisible(false);
    tela_sobre.setVisible(false);
    tela_cad_disco.setVisible(true);
    tela_cad_genero.setVisible(false);
    tela_consulta_disco.setVisible(false);
    tela_consulta_genero.setVisible(false);

    tab1_cad_disco.setBackground(new Color(232, 237, 223));
    tab2_cad_genero.setBackground(new Color(36, 36, 35));
    tab3_consul_disco.setBackground(new Color(36, 36, 35));
    tab4_consul_genero.setBackground(new Color(36, 36, 35));

    lb_cad_disco.setForeground(new Color(36, 36, 35));
    lb_cad_genero.setForeground(new Color(232, 237, 223));
    lb_consul_disco.setForeground(new Color(232, 237, 223));
    lb_consul_genero.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_tab1_cad_discoMouseClicked

  private void tab2_cad_generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2_cad_generoMouseClicked
    limparTabelaGeneros();
    limparTabelaDiscos();
    listaGeneros = factory.getTodosGeneros();
    combo_box_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(listaGeneros.toArray(new Genero[0])));
    tela_home.setVisible(false);
    tela_sobre.setVisible(false);
    tela_cad_disco.setVisible(false);
    tela_cad_genero.setVisible(true);
    tela_consulta_disco.setVisible(false);
    tela_consulta_genero.setVisible(false);

    tab1_cad_disco.setBackground(new Color(36, 36, 35));
    tab2_cad_genero.setBackground(new Color(232, 237, 223));
    tab3_consul_disco.setBackground(new Color(36, 36, 35));
    tab4_consul_genero.setBackground(new Color(36, 36, 35));

    lb_cad_disco.setForeground(new Color(232, 237, 223));
    lb_cad_genero.setForeground(new Color(36, 36, 35));
    lb_consul_disco.setForeground(new Color(232, 237, 223));
    lb_consul_genero.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_tab2_cad_generoMouseClicked

  private void tab3_consul_discoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3_consul_discoMouseClicked
    limparTabelaGeneros();
    listaDiscos = factory.getTodosDiscos();
    listaDiscos.forEach(disco -> {
      String genero = disco.getGenero() != null ?
          disco.getGenero().getNome() :
          "";
      modelDiscos.addRow(new Object[]{disco.getIdDisco(), disco.getTitulo(), disco.getAno(), genero});
    });
    tela_home.setVisible(false);
    tela_sobre.setVisible(false);
    tela_cad_disco.setVisible(false);
    tela_cad_genero.setVisible(false);
    tela_consulta_disco.setVisible(true);
    tela_consulta_genero.setVisible(false);

    tab1_cad_disco.setBackground(new Color(36, 36, 35));
    tab2_cad_genero.setBackground(new Color(36, 36, 35));
    tab3_consul_disco.setBackground(new Color(232, 237, 223));
    tab4_consul_genero.setBackground(new Color(36, 36, 35));

    lb_cad_disco.setForeground(new Color(232, 237, 223));
    lb_cad_genero.setForeground(new Color(232, 237, 223));
    lb_consul_disco.setForeground(new Color(36, 36, 35));
    lb_consul_genero.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_tab3_consul_discoMouseClicked

  private void tab4_consul_generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4_consul_generoMouseClicked
    limparTabelaDiscos();
    listaGeneros = factory.getTodosGeneros();
    listaGeneros.forEach(genero -> {
      if (genero != null) {
        String possuiSubgenero = genero.possuiSubgenero() ?
            "Sim" :
            "Não";
        modelGeneros.addRow(new Object[]{genero.getIdGenero(), genero.getNome(), genero.getNomeGeneroPai(), possuiSubgenero});
      }
    });
    tela_home.setVisible(false);
    tela_sobre.setVisible(false);
    tela_cad_disco.setVisible(false);
    tela_cad_genero.setVisible(false);
    tela_consulta_disco.setVisible(false);
    tela_consulta_genero.setVisible(true);

    tab1_cad_disco.setBackground(new Color(36, 36, 35));
    tab2_cad_genero.setBackground(new Color(36, 36, 35));
    tab3_consul_disco.setBackground(new Color(36, 36, 35));
    tab4_consul_genero.setBackground(new Color(232, 237, 223));

    lb_cad_disco.setForeground(new Color(232, 237, 223));
    lb_cad_genero.setForeground(new Color(232, 237, 223));
    lb_consul_disco.setForeground(new Color(232, 237, 223));
    lb_consul_genero.setForeground(new Color(36, 36, 35));
  }//GEN-LAST:event_tab4_consul_generoMouseClicked

  private void input_cad_disco_nomeActionPerformed() {//GEN-FIRST:event_input_cad_disco_nomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_input_cad_disco_nomeActionPerformed

  private void input_cad_disco_anoActionPerformed() {//GEN-FIRST:event_input_cad_disco_anoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_input_cad_disco_anoActionPerformed

  private void combo_box_generoActionPerformed() {//GEN-FIRST:event_combo_box_generoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_combo_box_generoActionPerformed

  private void label_cancelarMouseClicked() {//GEN-FIRST:event_label_cancelarMouseClicked
    tela_home.setVisible(true);
    tela_cad_disco.setVisible(false);
    tab1_cad_disco.setBackground(new Color(36, 36, 35));
    lb_cad_disco.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_label_cancelarMouseClicked

  private void input_cad_genero_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cad_genero_nomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_input_cad_genero_nomeActionPerformed

  private void label_cancelar_genMouseClicked() {//GEN-FIRST:event_label_cancelar_genMouseClicked
    tela_home.setVisible(true);
    tela_cad_genero.setVisible(false);
    tab2_cad_genero.setBackground(new Color(36, 36, 35));
    lb_cad_genero.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_label_cancelar_genMouseClicked

  private void btn_sobreMouseClicked() {//GEN-FIRST:event_btn_sobreMouseClicked
        tela_home.setVisible(false);
        tela_sobre.setVisible(true);
        tela_cad_disco.setVisible(false);
        tela_cad_genero.setVisible(false);
        tela_consulta_disco.setVisible(false);
        tela_consulta_genero.setVisible(false);

        tab1_cad_disco.setBackground(new Color(36, 36, 35));
        tab2_cad_genero.setBackground(new Color(36, 36, 35));
        tab3_consul_disco.setBackground(new Color(36, 36, 35));
        tab4_consul_genero.setBackground(new Color(36, 36, 35));
        label_sobre.setForeground(new Color(36,36,35));

        lb_cad_disco.setForeground(new Color(232,237,223));
        lb_cad_genero.setForeground(new Color(232,237,223));
        lb_consul_disco.setForeground(new Color(232,237,223));
        lb_consul_genero.setForeground(new Color(232,237,223));
        btn_sobre.setBackground(new Color(232,237,223));
  }//GEN-LAST:event_btn_sobreMouseClicked

  private void label_desligaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_desligaMouseClicked
    System.exit(0);
  }//GEN-LAST:event_label_desligaMouseClicked

  private void label_voltar_discoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_voltar_discoMouseClicked
    tela_home.setVisible(true);
    tela_consulta_disco.setVisible(false);
    tab3_consul_disco.setBackground(new Color(36, 36, 35));
    lb_consul_disco.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_label_voltar_discoMouseClicked

  private void label_voltar_genMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_voltar_genMouseClicked
    tela_home.setVisible(true);
    tela_consulta_genero.setVisible(false);
    tab4_consul_genero.setBackground(new Color(36, 36, 35));
    lb_consul_genero.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_label_voltar_genMouseClicked

  private void label_voltar_sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_voltar_sobreMouseClicked
    tela_home.setVisible(true);
    tela_sobre.setVisible(false);
    btn_sobre.setBackground(new Color(36, 36, 35));
    label_sobre.setForeground(new Color(232, 237, 223));
  }//GEN-LAST:event_label_voltar_sobreMouseClicked

  private void limparCampos() {
    input_cad_disco_ano.setText("");
    input_cad_disco_nome.setText("");
    input_cad_genero_nome.setText("");
  }

  private void limparTabelaGeneros() {
    int quantidadeGeneros = modelGeneros.getRowCount();
    for (int i = 0; i < quantidadeGeneros; i++) {
      modelGeneros.removeRow(0);
    }
  }

  private void limparTabelaDiscos() {
    int quantidadeDiscos = modelDiscos.getRowCount();
    for (int i = 0; i < quantidadeDiscos; i++) {
      modelDiscos.removeRow(0);
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel andrey;
  private javax.swing.JLabel background;
  private javax.swing.JPanel btn_buscar_disco;
  private javax.swing.JPanel btn_buscar_genero;
  private javax.swing.JPanel btn_cadastrar_disco;
  private javax.swing.JPanel btn_cadastrar_genero;
  private javax.swing.JPanel btn_desliga;
  private javax.swing.JPanel btn_sobre;
  private javax.swing.JPanel btn_voltar_cad_disco;
  private javax.swing.JPanel btn_voltar_cad_gen;
  private javax.swing.JPanel btn_voltar_con_disco;
  private javax.swing.JPanel btn_voltar_con_gen;
  private javax.swing.JPanel btn_voltar_sobre;
  private javax.swing.JComboBox<Genero> combo_box_genero;
  private javax.swing.JComboBox<Genero> combo_box_grupo;
  private javax.swing.JPanel home;
  private javax.swing.JTextField input_cad_disco_ano;
  private javax.swing.JTextField input_cad_disco_nome;
  private javax.swing.JTextField input_cad_genero_nome;
  private javax.swing.JTextField input_consulta_disco;
  private javax.swing.JTextField input_consulta_genero;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane_disco;
  private javax.swing.JScrollPane jScrollPane_genero;
  private javax.swing.JTable jTable_disco;
  private javax.swing.JTable jTable_genero;
  private javax.swing.JLabel label_ano;
  private javax.swing.JLabel label_buscar_disco;
  private javax.swing.JLabel label_buscar_gen;
  private javax.swing.JLabel label_cadastrar;
  private javax.swing.JLabel label_cadastrar_gen;
  private javax.swing.JLabel label_cancelar;
  private javax.swing.JLabel label_cancelar_gen;
  private javax.swing.JLabel label_desliga;
  private javax.swing.JLabel label_genero;
  private javax.swing.JLabel label_grupo;
  private javax.swing.JLabel label_nome_disco;
  private javax.swing.JLabel label_nome_gen;
  private javax.swing.JLabel label_sobre;
  private javax.swing.JLabel label_voltar_disco;
  private javax.swing.JLabel label_voltar_gen;
  private javax.swing.JLabel label_voltar_sobre;
  private javax.swing.JLabel lb_cad_disco;
  private javax.swing.JLabel lb_cad_genero;
  private javax.swing.JLabel lb_cadastro;
  private javax.swing.JLabel lb_consul_disco;
  private javax.swing.JLabel lb_consul_genero;
  private javax.swing.JLabel lb_consulta;
  private javax.swing.JLabel logo;
  private javax.swing.JPanel painel_creditos;
  private javax.swing.JLabel ryan;
  private javax.swing.JPanel sideMenu;
  private javax.swing.JPanel tab1_cad_disco;
  private javax.swing.JPanel tab2_cad_genero;
  private javax.swing.JPanel tab3_consul_disco;
  private javax.swing.JPanel tab4_consul_genero;
  private javax.swing.JPanel tela_cad_disco;
  private javax.swing.JPanel tela_cad_genero;
  private javax.swing.JPanel tela_consulta_disco;
  private javax.swing.JPanel tela_consulta_genero;
  private javax.swing.JPanel tela_home;
  private javax.swing.JPanel tela_sobre;
  private javax.swing.JLabel title_cad_disco;
  private javax.swing.JLabel title_cad_genero;
  private javax.swing.JLabel title_con_disco;
  private javax.swing.JLabel title_con_genero;
  private javax.swing.JPanel topBar;
  // End of variables declaration//GEN-END:variables
}